# Analysis on Hz4 Galex FUV

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage

In [2]:
from astropy.io import fits

In [3]:
hdul = fits.open("G:/NAXATRA/UVIT_IUCAA_2020/hz4_galex_chopped_fuv.fits")

In [4]:
hdul.info()

Filename: G:/NAXATRA/UVIT_IUCAA_2020/hz4_galex_chopped_fuv.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      19   (740, 472)   float32   


In [5]:
data = hdul[0].data

In [6]:
data.shape

(472, 740)

In [7]:
data[158][200]       #xleft

0.0017092935

In [8]:
data[469][200]       #xright

0.0012918746

In [9]:
data[200][84]       #ytop

0.0

In [10]:
data[200][454]       #ybottom

0.0014519535

In [11]:
set_a = (158,84)

In [12]:
short = data[158:469, 84:454]

In [13]:
print(short)

[[0.         0.         0.         ... 0.00132532 0.001148   0.00132392]
 [0.         0.         0.         ... 0.00145811 0.00128069 0.00141243]
 [0.         0.         0.         ... 0.0012816  0.00154594 0.00119216]
 ...
 [0.00118048 0.00139293 0.00110159 ... 0.00126753 0.00130956 0.00147854]
 [0.00156535 0.00075557 0.00121714 ... 0.001605   0.00084474 0.001605  ]
 [0.00142839 0.00187993 0.00108985 ... 0.00177365 0.00147779 0.00126689]]


In [14]:
# test_arr = data[310:323, 260:273]

In [15]:
# short = test_arr

In [16]:
short.shape

(311, 370)

In [17]:
short

array([[0.        , 0.        , 0.        , ..., 0.00132532, 0.001148  ,
        0.00132392],
       [0.        , 0.        , 0.        , ..., 0.00145811, 0.00128069,
        0.00141243],
       [0.        , 0.        , 0.        , ..., 0.0012816 , 0.00154594,
        0.00119216],
       ...,
       [0.00118048, 0.00139293, 0.00110159, ..., 0.00126753, 0.00130956,
        0.00147854],
       [0.00156535, 0.00075557, 0.00121714, ..., 0.001605  , 0.00084474,
        0.001605  ],
       [0.00142839, 0.00187993, 0.00108985, ..., 0.00177365, 0.00147779,
        0.00126689]], dtype=float32)

In [18]:
np.mean(short)

0.001752578

In [19]:
np.std(short)

0.022472914

In [20]:
#making a 1D array of the short array
short_line_pre = short.flatten()

print (short_line_pre)

[0.         0.         0.         ... 0.00177365 0.00147779 0.00126689]


In [21]:
#remove the 0 values because of some error in the image 
short_line = short_line_pre[short_line_pre>0]

print(short_line)

[0.0011935  0.00115025 0.00138754 ... 0.00177365 0.00147779 0.00126689]


In [22]:
mn = np.mean(short_line)
print(mn)

0.0019138419


In [23]:
std = np.std(short_line)
print(std)

0.02347752


Edit from here

In [55]:
#thres = mn + 3*std     #for 1*std the results were good as compared to 13*13 array observation
print(thres)

0.0022991271689534187


In [56]:
short_line.shape

(105374,)

In [57]:
#modify the array to remove exceeding values than threshold
modif_short_line = short_line[short_line < thres]
print(modif_short_line)

[0.0011935  0.00115025 0.00138754 ... 0.00177365 0.00147779 0.00126689]


In [58]:
modif_mn = np.mean(modif_short_line)
print(modif_mn)

0.0014582294


In [59]:
modif_std = np.std(modif_short_line)
print(modif_std)

0.0002801906


In [61]:
thres = modif_mn + 3*modif_std
print(thres)

0.0022988012060523033


In [9]:
short = data

# Method 2 - Checking each point greater than given value and eleminating it if not max of the focus array

   #  Give value of V

In [7]:
V = 0.00229                                                                                   #the minima value
print('Given minimum value: ', V)

Given minimum value:  0.00229


In [10]:
length = len(short)
store_arr = np.zeros(length*length*3)


In [67]:
#specify the range to be observed
q = 0
for i in range(0,472):                                           #taking all points above V and choosing and printing
    for j in range(0,740):
        if (short[i][j]>=V):
            print(short[i][j], 'at point:', i, ',', j)
            store_arr[q] = short[i][j]
            q = q+1
            store_arr[q] = i
            q = q+1
            store_arr[q] = j
            q = q+1
            


0.0051755174 at point: 304 , 268
0.0056848945 at point: 305 , 261
0.005186722 at point: 305 , 262
0.005409304 at point: 305 , 264
0.005903028 at point: 305 , 265
0.0052252254 at point: 305 , 266
0.005673631 at point: 305 , 267
0.0054455446 at point: 305 , 268
0.0051717935 at point: 305 , 270
0.0062680375 at point: 306 , 262
0.006041479 at point: 306 , 263
0.0061305445 at point: 306 , 264
0.0059931506 at point: 306 , 265
0.0064414414 at point: 306 , 266
0.0071145534 at point: 306 , 267
0.0054915375 at point: 306 , 268
0.005322988 at point: 307 , 260
0.006990799 at point: 307 , 261
0.007034632 at point: 307 , 262
0.0077096485 at point: 307 , 263
0.0075730258 at point: 307 , 264
0.007795602 at point: 307 , 265
0.007657658 at point: 307 , 266
0.007295983 at point: 307 , 267
0.006482982 at point: 307 , 268
0.0061656167 at point: 307 , 269
0.005803491 at point: 307 , 270
0.007126105 at point: 308 , 260
0.00712482 at point: 308 , 261
0.008477634 at point: 308 , 262
0.008476105 at point: 308 ,

In [11]:
#check
print(store_arr[0:30])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [12]:
a = int(store_arr[1])
b = int(store_arr[2])
print ('Point chosen:', a,b, 'with value', short[a][b])


Point chosen: 0 0 with value nan


# Set the value N

In [13]:
#set focus matrix to zero and then take values with chosen point at centre
N = 1
t = 2*N+1

focus = np.zeros((t, t))                             

for i in range(0,t):
    for j in range(0,t):
        focus[i][j] = short [a-N+i][b-N+j]
        
print('Focus \n',focus)

r = max(map(max, focus))
print('\n',r)

Focus 
 [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]

 nan


In [14]:
#While loop starts to scan over the short array

l = 0
while(focus[N][N] != r):
    
    a = int(store_arr[1+(3*l)])
    b = int(store_arr[2+(3*l)])
#    print ('Point chosen:', a,b, 'with value', short[a][b])

    focus = np.zeros((t, t))                             

    for i in range(0,t):
        for j in range(0,t):
            focus[i][j] = short [a-N+i][b-N+j]

#    print('Focus \n',focus)

    r = max(map(max, focus))
#    print('\n',r)
    l = l+1
    
print('New Focus \n',focus)

IndexError: index 668353 is out of bounds for axis 0 with size 668352

In [76]:
#Final results 

print('Position of the point in Short Matrix: ', a, b)
Sum = focus.sum()
print('Sum of all values : ', Sum)
Centroid = ndimage.measurements.center_of_mass(focus)
cen_result = tuple(map(sum, zip(Centroid, (a-N,b-N))))
print('Centroid is at', cen_result)

Position of the point in Short Matrix:  315 264
Sum of all values :  43.71127034910023
Centroid is at (315.1688695621881, 264.11096682043825)
