# Analysis on Hz4 Galex FUV

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage
import pandas as pd

In [2]:
from astropy.io import fits

In [3]:
Stars = []

In [4]:
hdul = fits.open("G:/NAXATRA/UVIT_IUCAA_2020/hz4_galex_chopped_fuv.fits")

In [5]:
hdul.info()

Filename: G:/NAXATRA/UVIT_IUCAA_2020/hz4_galex_chopped_fuv.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      19   (740, 472)   float32   


In [6]:
data = hdul[0].data

In [7]:
data.shape

(472, 740)

In [8]:
short = data

#We get the array of pixel values around the star. The area observed is about 20 pixel side square.

In [9]:
print(short)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [10]:
type(short)

numpy.ndarray

# Method 2 - Checking each point greater than given value and eleminating it if not max of the focus array

   #  Give value of V

In [11]:
V = 0.002863                                                                                   #the minima value
print('Given minimum value: ', V)

Given minimum value:  0.002863


In [12]:
length = len(short)
store_arr = np.zeros(length*length*3)


In [13]:
#specify the range to be observed
q = 0
for i in range(0,472):                                           #taking all points above V and choosing and printing
    for j in range(0,740):
        if (short[i][j]>=V):
            print(short[i][j], 'at point:', i, ',', j)
            store_arr[q] = short[i][j]
            q = q+1
            store_arr[q] = i
            q = q+1
            store_arr[q] = j
            q = q+1
            


0.0029119789 at point: 235 , 139
0.0029118136 at point: 280 , 133
0.0030321407 at point: 282 , 121
0.0031227372 at point: 290 , 259
0.0028964519 at point: 291 , 259
0.0029406443 at point: 291 , 260
0.002988048 at point: 292 , 258
0.0029853447 at point: 292 , 260
0.0029864253 at point: 293 , 259
0.0029395802 at point: 293 , 260
0.0030294808 at point: 295 , 260
0.0029401123 at point: 296 , 259
0.0029735088 at point: 296 , 266
0.0030125899 at point: 296 , 269
0.003010424 at point: 296 , 270
0.0034277467 at point: 297 , 264
0.0032432433 at point: 297 , 266
0.002920036 at point: 297 , 270
0.0029591105 at point: 297 , 273
0.0029038598 at point: 297 , 279
0.003203393 at point: 298 , 263
0.003334535 at point: 298 , 265
0.003242659 at point: 298 , 266
0.0029702971 at point: 298 , 267
0.003013674 at point: 298 , 268
0.002977203 at point: 299 , 135
0.0029422415 at point: 299 , 257
0.002985885 at point: 299 , 258
0.003026197 at point: 299 , 261
0.0031053105 at point: 299 , 267
0.003013674 at point

0.2768163 at point: 312 , 265
0.17222422 at point: 312 , 266
0.083438456 at point: 312 , 267
0.037882883 at point: 312 , 268
0.017699514 at point: 312 , 269
0.010987031 at point: 312 , 270
0.0074270796 at point: 312 , 271
0.0046804682 at point: 312 , 272
0.0051736548 at point: 312 , 273
0.003868298 at point: 312 , 274
0.004406475 at point: 312 , 275
0.003460363 at point: 312 , 276
0.0035932446 at point: 312 , 277
0.0030526128 at point: 312 , 278
0.0030240116 at point: 313 , 248
0.0030674846 at point: 313 , 249
0.0033820346 at point: 313 , 250
0.0039210385 at point: 313 , 251
0.0038295188 at point: 313 , 252
0.0036486487 at point: 313 , 253
0.004007565 at point: 313 , 254
0.0049972986 at point: 313 , 255
0.0064379615 at point: 313 , 256
0.009681196 at point: 313 , 257
0.015267519 at point: 313 , 258
0.038288288 at point: 313 , 259
0.09983781 at point: 313 , 260
0.2494142 at point: 313 , 261
0.52960527 at point: 313 , 262
0.8119704 at point: 313 , 263
0.9403281 at point: 313 , 264
0.7711

0.0030487804 at point: 326 , 251
0.0036309843 at point: 326 , 253
0.0030487804 at point: 326 , 254
0.0031838566 at point: 326 , 255
0.004754216 at point: 326 , 256
0.004397774 at point: 326 , 257
0.0039055485 at point: 326 , 258
0.0049847313 at point: 326 , 259
0.0049856273 at point: 326 , 260
0.005121294 at point: 326 , 261
0.004806828 at point: 326 , 262
0.004806828 at point: 326 , 263
0.005435759 at point: 326 , 264
0.0052560647 at point: 326 , 265
0.004805965 at point: 326 , 266
0.0045364713 at point: 326 , 267
0.0036375066 at point: 326 , 268
0.0041763964 at point: 326 , 269
0.0034578769 at point: 326 , 270
0.0034129692 at point: 326 , 271
0.0029184627 at point: 326 , 272
0.0031861425 at point: 326 , 275
0.0033614198 at point: 327 , 253
0.00295858 at point: 327 , 254
0.0037206383 at point: 327 , 255
0.0034080718 at point: 327 , 256
0.0030504216 at point: 327 , 257
0.0037246456 at point: 327 , 258
0.004668702 at point: 327 , 259
0.0037715517 at point: 327 , 260
0.0037715517 at poin

In [14]:
print(store_arr[0:30])

[2.91197887e-03 2.35000000e+02 1.39000000e+02 2.91181356e-03
 2.80000000e+02 1.33000000e+02 3.03214067e-03 2.82000000e+02
 1.21000000e+02 3.12273717e-03 2.90000000e+02 2.59000000e+02
 2.89645186e-03 2.91000000e+02 2.59000000e+02 2.94064428e-03
 2.91000000e+02 2.60000000e+02 2.98804790e-03 2.92000000e+02
 2.58000000e+02 2.98534473e-03 2.92000000e+02 2.60000000e+02
 2.98642530e-03 2.93000000e+02 2.59000000e+02 2.93958024e-03
 2.93000000e+02 2.60000000e+02]


In [15]:

a = int(store_arr[1])
b = int(store_arr[2])
print ('Point chosen:', a,b, 'with value', short[a][b])


Point chosen: 235 139 with value 0.0029119789


# Set the value N

In [16]:
#set focus matrix to zero and then take values with chosen point at centre
N = 1
t = 2*N+1

focus = np.zeros((t, t))                             

for i in range(0,t):
    for j in range(0,t):
        focus[i][j] = short [a-N+i][b-N+j]
        
print('Focus \n',focus)

r = max(map(max, focus))
print('\n',r)

Focus 
 [[0.00194336 0.00200857 0.00168372]
 [0.00164541 0.00291198 0.00128074]
 [0.00189908 0.00157233 0.00164891]]

 0.002911978866904974


In [17]:
#While loop starts to scan over the short array

l = 0
while(focus[N][N] != r):
    
    a = int(store_arr[1+(3*l)])
    b = int(store_arr[2+(3*l)])
    print ('Point chosen:', a,b, 'with value', short[a][b])

    focus = np.zeros((t, t))                             

    for i in range(0,t):
        for j in range(0,t):
            focus[i][j] = short [a-N+i][b-N+j]

    print('Focus \n',focus)

    r = max(map(max, focus))
    print('\n',r)
    l = l+1
    
print('New Focus \n',focus)

New Focus 
 [[0.00194336 0.00200857 0.00168372]
 [0.00164541 0.00291198 0.00128074]
 [0.00189908 0.00157233 0.00164891]]


In [18]:
#Final results

print('Position of the point in Short Matrix: ', a, b)
Sum = focus.sum()
print('Sum of all values : ', Sum)
Centroid = ndimage.measurements.center_of_mass(focus)
print('Centroid is at', Centroid)

Position of the point in Short Matrix:  235 139
Sum of all values :  0.01659409806597978
Centroid is at (0.9689443443972813, 0.9473011914778904)


Edits

In [19]:
Stars.append((a,b,short[a][b],focus[N][N]))
print(Stars)



[(235, 139, 0.0029119789, 0.002911978866904974)]


In [20]:
len(store_arr)

668352

In [21]:
len_store_arr = store_arr[store_arr>0]

In [22]:
len(len_store_arr)

2556

In [23]:
total_pixels = int(len(len_store_arr)/3)
total_pixels

852

In [24]:
counter = 0

In [25]:
while (l<total_pixels-1):
    l += 1
    a = int(store_arr[1+(3*l)])
    b = int(store_arr[2+(3*l)])

    focus = np.zeros((t, t))                             

    for i in range(0,t):
        for j in range(0,t):
            focus[i][j] = short [a-N+i][b-N+j]

#    print('Focus \n',focus)

    r = max(map(max, focus))

    while(focus[N][N] != r):

        a = int(store_arr[1+(3*l)])
        b = int(store_arr[2+(3*l)])
#        print ('Point chosen:', a,b, 'with value', short[a][b])

        focus = np.zeros((t, t))                             

        for i in range(0,t):
            for j in range(0,t):
                focus[i][j] = short [a-N+i][b-N+j]

#        print('Focus \n',focus)

        r = max(map(max, focus))
#        print('\n',r)
        l = l+1

#    print('New Focus \n',focus)


#    print('Position of the point in Short Matrix: ', a, b)


    Stars.append((a,b,short[a][b],focus[N][N]))
#    print(Stars)

In [26]:
print(Stars)

[(235, 139, 0.0029119789, 0.002911978866904974), (280, 133, 0.0029118136, 0.0029118135571479797), (282, 121, 0.0030321407, 0.003032140666618943), (290, 259, 0.0031227372, 0.0031227371655404568), (292, 258, 0.002988048, 0.0029880478978157043), (295, 260, 0.0030294808, 0.0030294808093458414), (296, 269, 0.0030125899, 0.0030125898774713278), (297, 264, 0.0034277467, 0.003427746705710888), (297, 273, 0.0029591105, 0.002959110541269183), (299, 135, 0.002977203, 0.0029772031120955944), (300, 258, 0.0032567396, 0.0032567395828664303), (300, 273, 0.00367713, 0.003677129978314042), (301, 256, 0.0031227372, 0.0031227371655404568), (302, 254, 0.0031702898, 0.003170289797708392), (302, 269, 0.0048120166, 0.0048120166175067425), (302, 282, 0.0029485347, 0.0029485346749424934), (303, 262, 0.00428623, 0.0042862300761044025), (303, 266, 0.004773915, 0.004773914813995361), (303, 274, 0.0034965035, 0.003496503457427025), (305, 253, 0.0035281347, 0.0035281346645206213), (305, 270, 0.0051717935, 0.0051717

In [27]:
len(Stars)

74

In [28]:
import csv

In [29]:
import pandas as pd  

In [30]:
df = pd.DataFrame(Stars)

In [31]:
df.to_csv('Star_positions.csv')